### ISSUE TITLE
Only serial published

### ISSUE THREAD

**Issue by DrDOIS** [victronenergy/dbus-mqtt#13]
Hi,

after installing Venus OS on my Raspberry, I enabed the "MQTT on LAN (plaintext)" option and connected to the broker on the Pi. 
Except for the serial on topic `N/b8.../system/0/Serial` no other data was published.

After having a look at the code, the issue seems to be related to the _keep_alive_timer which is always None.
As  the _keep_alive_interval is 60 by default, the following condition in the _publish function is met leading to a `return` call.
https://github.com/victronenergy/dbus-mqtt/blob/fb8e3eeb2e8237749f6d06ef1975fa3215e985ad/dbus_mqtt.py#L82

The timer seems to be set only after receiving a message via mqtt. Is this behaviour intentional?
A simple workaround is to call the script with a keep_alive of 0, like:
` /usr/bin/python -u /opt/victronenergy/dbus-mqtt/dbus_mqtt.py --init-broker -k 0`

**Comment by thlassche** [comment]
Hi,

That is intentional, see https://github.com/victronenergy/dbus-mqtt#keep-alive for more details
