### ISSUE TITLE
Write only happen one time. How to make it continuously

### ISSUE THREAD

**Issue by plpento** [victronenergy/dbus-mqtt#15]
Hi,

I have tested to control my Cerbo GX with MQTT but I send for example the command to W/<id>/system/0/Buzzer/State.
The buzzer only bip one time and the value goes to 0.

I would like to make it continously to control a relay.
Is it possible?

Thanks,

Panagiotis

**Comment by mpvader** [comment]
Hi, that buzzer is controlled by internal victron software. So, makes sense you can't freely control it.

To control a relay, you need to first disable the internal control of that relay. See settigns -> relay -> mode -> manual control or something like that.

for any similar questions or followup questions, please use https://community.victronenergy.com - > Mods space. Thanks!
