### ISSUE TITLE
setting QoS to 1 or 2

### ISSUE THREAD

**Issue by Besenreiter** [victronenergy/dbus-mqtt#17]
Hello,
I use your project with Venus on a Pi3. A second Pi conects to the broker on the Venus and collects the data. Every now and then the data is not received and stops receiving from this point in time. But the data is on the net as I can see it with a third machine using MQTT-Explorer. There I can see that the Victron broker is using QoS = 0. It would be nice to be able to set this to QoS=1 or 2. I looked at the Python script, but can't figure out what I have to change to achive this.
Could you explain that?
Thanks.

**Comment by mpvader** [comment]
Hi @Besenreiter , using QoS will not solve problems where data receival stops and then not resumes.

There is a lot more to say about MQTT QoS, which is quite a complicated topic. But thats not something we (Victron) can get into now or help you with I'm afraid.

I do recommend reading this post: https://www.flashmq.org/2022/11/26/understanding-clean-session-and-clean-start/.

**Comment by Besenreiter** [comment]
OK, thabks for the answer.
