### ISSUE TITLE
Is there really an advantage in using JSON format as standard output for all topics - which uses extra resources

### ISSUE THREAD

**Issue by VanillaFord** [victronenergy/dbus-mqtt#18]
Quite a new and happy user here. Thank you for making VenusOS and the use of MQTT available to the Community!

I couldn't help but notice, that in the +1000 topics available only a few (less than 10, AFAI did see) are really using a more complex information in their value string, that would justify the use of a serialized JSON object.
All other topics actually contain one information item only, therefore basically wasting a lot of bytes and bandwidth when publishing and causing some extra load when parsing on the subscriber side.

If I calculated the Broker info correctly, my Cerbo publishes roughly 3900 msg per minute, each containing the string {"value": } in its topic, besides the data value itself, so "wasting" 10 bytes each, resulting in extra consumed bandwidth of 39kbytes/minute.

Many thanks in advance for considering an answer.
regards,
Ford

**Comment by mpvader** [comment]
Hi Ford, yes that will help you are right. What will help even more is to use topic aliasses; part of MQTT 5.

We're working towards using topic aliasses. And after that can look at things like this; but note that that will be a big change; will need backwards compatibility for older versions of VictronConnect, or customers that made implementations, and so forth.

**Comment by VanillaFord** [comment]
Yes, I agree, that a migration path need to be found. However, a MQTT client can very well handle the detection and marshalling between raw and JSON values, as this is already the case with the Node-Red mqttt-in node for example.
Thanks for letting us know, what plans are ahead. Keep up the good work and stay safe!

regards,
Ford
