### ISSUE TITLE
/keepalive method not working on Cerbo with firmware version 2.94

### ISSUE THREAD

**Issue by nicopret1** [victronenergy/dbus-mqtt#19]
I've implemented the /keepalive method with a Home Assistant Automation, but it does not work. If I replace  
"R/c0847d9b49b3/keepalive" with "R/c0847d9b49b3/system/0/Serial" in my automation.yaml file it works perfectly.
The automation executes very 30s. My CerboGX firmware version is 2.94.

Below the content of my automation.yaml
`alias: Refresh MQTT Victron
description: Request the data on the MQTT server
trigger:
  - platform: time_pattern
    seconds: /30
condition: []
action:
  - service: mqtt.publish
    data:
      topic: victron-home/R/c0847d9b49b3/system/0/Serial
      payload: >-
        {["system/0/Dc/Battery/Soc","settings/0/Settings/CGwacs/BatteryLife/SocLimit","system/0/Dc/Battery/Voltage","system/0/Dc/Battery/Temperature","system/0/Dc/Battery/Power","system/0/Ac/Consumption/+/Power","system/0/Ac/Grid/+/Power","grid/30/Ac/Power","system/0/Dc/Pv/Power","battery/512/Soc","solarcharger/+/Yield/Power",,"solarcharger/+/State","system/0/Ac/ActiveIn/Source","system/0/SystemState/State"]}
mode: single`

**Comment by mpvader** [comment]
Hey @nicopret1 , thank you for the report! That is strange that it doesn't work for you.

We're retiring dbus-mqtt. See this issue for details: https://github.com/victronenergy/venus/issues/1098.

Conclusion would be to, if above is an issue for you, please test using flashmq. We will not be putting any more effort into dbus-mqtt.

**Comment by nicopret1** [comment]
Thank you for the feedback @mpvader. I'll checkout flashmq
