### ISSUE TITLE
Websockets in local network

### ISSUE THREAD

**Issue by DioBal** [victronenergy/dbus-mqtt#6]
Hello, as title says, is it possible to access the mqtt through a websocket in the local network? (not using the victron site)

**Comment by LeeNX** [comment]
From https://community.openhab.org/t/mqtt-interface-to-victron-ccgx/43888  
  
I was able to use mosquitto on Linux, I have been able to access the MQTT topics.  
  
Basically you need to pull the CCGX VRM Portal ID, doing something like
```
mosquitto_sub -h 192.168.0.100 -t "#"
```
```
{"value": "a0f6fd5aa8c8"}
```
Then you let your CCGX know you listening for topics with
```
mosquitto_pub -h 192.168.0.100 -t "R/a0f6fd5aa8c8/system/0/Serial" -m ""
```
Suggestion is to do this every 30sec  
  
Then subscript to topics with something like
```
mosquitto_sub -h 192.168.0.100 -t "N/#" -v
```
or 
```
mosquitto_sub -h 192.168.0.100 -t "N/a0f6fd5aa8c8/system/0/Ac/Consumption/L1/Power" -v
```
Hope this helps. Might be an idea to add to the documentation.  
  
Investigating if I can setup a bridge to a local mosquitto install. Just seems like a lot of hoops to get data.

**Comment by mpvader** [comment]
> Hello, as title says, is it possible to access the mqtt through a websocket in the local network? (not using the victron site)

Hi!

At the moment its not, at least not by default.

However, I think websockify is availble in Venus OS: making it work should be a one-liner.

Also we’ll be looking into this ourselves, for a project we are doing soon.

Lastly, sorry for the slow reply. We dont monitor issues on the various sub repos. Next time, please use the developers mailinglist for questions, and the Venus repo on github for issues.

Thanks!
