### ISSUE TITLE
Local only MQTT

### ISSUE THREAD

**Issue by IVI053** [victronenergy/dbus-mqtt#8]
Is there a reason that enabling MQTT in Venus is tied to also publishing the data to Victrons MQTT server without an easy option to disable this?

**Comment by mbfrydman** [comment]
Right now the only way to work around this is through the mqtt config files by removing the victron server and replacing with your local server.

**Comment by mpvader** [comment]
Is it? Since I think venus OS v2.40, enabling the VRM Two Way Communication setting enables the mosquitto bridge config.

When disabled, its all only local.

**Comment by mbfrydman** [comment]
Ohh, missed that change. That's cool! Thanks for pointing it out.

**Comment by mpvader** [comment]
I had to rethink it myself too.

But now, both mqtt clients in Venus OS connect to the local mosquitto broker.

More details here: https://github.com/victronenergy/venus/issues/480

I’ll close this issue now

**Comment by pkkrusty** [comment]
An old issue, but it speaks to what I'm trying to figure out. If I only want local MQTT and not VRM uploaded MQTT (for my own bandwidth reasons and to save Victron the marginal processing cost), I can disable Enable 2-way Communication.  Does disabling this turn off other important communication, or is it solely the MQTT bridge?
